In [2]:
import pandas as pd
import numpy as np
import collections

In [5]:
pui_filename = 'datasets/hm/purchase_user_item.csv'
pui_df = pd.read_csv(pui_filename, index_col = 0)
pui_df

,user_id,age,postal_code,item_id,price,timestamp,count,occurence,product_code,product_type_no,graphical_appearance_no,colour_group_code,perceived_colour_value_id,perceived_colour_master_id,department_no,index_group_no,section_no,garment_group_no
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,625548001,0.044051,2018-12-27,19,0,625548,262,1010016,73,4,2,8852,4,45,1007
1,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,176209023,0.035576,2018-12-27,19,1,176209,308,1010016,9,4,5,5283,3,31,1007
2,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,627759010,0.030492,2018-12-27,19,2,627759,262,1010016,73,4,2,7812,4,45,1007
3,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,697138006,0.010153,2019-05-02,19,3,697138,267,1010001,51,1,4,7616,4,76,1005
4,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,568601006,0.050831,2019-05-25,19,4,568601,264,1010016,9,4,5,1212,1,11,1008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28575390,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,866755002,0.043203,2020-04-09,7,3,866755,265,1010023,72,2,2,1344,2,53,1013
28575391,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,840360003,0.013542,2020-04-09,7,4,840360,255,1010007,10,3,9,1640,2,53,1005
28575392,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,866755002,0.050831,2020-04-25,7,5,866755,265,1010023,72,2,2,1344,2,53,1013
28575393,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,882810001,0.016932,2020-06-22,7,6,882810,286,1010016,31,1,3,1339,1,61,1017
28575394,ffffd9ac14e89946416d80e791d064701994755c3ab686...,65.0,0a1a03306fb2f62164c2a439b38c0caa64b40deaae8687...,806050001,0.084729,2019-12-04,1,0,806050,87,1010016,9,4,5,3529,1,64,1020

In [59]:
len(pui_df['postal_code'].value_counts())

352336

In [52]:
pui_df.dropna(axis = 0)

,user_id,age,postal_code,item_id,price,timestamp,count,occurence,product_code,product_type_no,graphical_appearance_no,colour_group_code,perceived_colour_value_id,perceived_colour_master_id,department_no,index_group_no,section_no,garment_group_no
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,625548001,0.044051,2018-12-27,19,0,625548,262,1010016,73,4,2,8852,4,45,1007
1,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,176209023,0.035576,2018-12-27,19,1,176209,308,1010016,9,4,5,5283,3,31,1007
2,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,627759010,0.030492,2018-12-27,19,2,627759,262,1010016,73,4,2,7812,4,45,1007
3,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,697138006,0.010153,2019-05-02,19,3,697138,267,1010001,51,1,4,7616,4,76,1005
4,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,568601006,0.050831,2019-05-25,19,4,568601,264,1010016,9,4,5,1212,1,11,1008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28575390,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,866755002,0.043203,2020-04-09,7,3,866755,265,1010023,72,2,2,1344,2,53,1013
28575391,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,840360003,0.013542,2020-04-09,7,4,840360,255,1010007,10,3,9,1640,2,53,1005
28575392,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,866755002,0.050831,2020-04-25,7,5,866755,265,1010023,72,2,2,1344,2,53,1013
28575393,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...,882810001,0.016932,2020-06-22,7,6,882810,286,1010016,31,1,3,1339,1,61,1017
28575394,ffffd9ac14e89946416d80e791d064701994755c3ab686...,65.0,0a1a03306fb2f62164c2a439b38c0caa64b40deaae8687...,806050001,0.084729,2019-12-04,1,0,806050,87,1010016,9,4,5,3529,1,64,1020

In [70]:
pui_df['garment_group_no'].astype('category')

0           1007
1           1007
2           1007
3           1005
4           1008
            ...
28575390    1013
28575391    1005
28575392    1013
28575393    1017
28575394    1020
Name: garment_group_no, Length: 28575395, dtype: category
Categories (21, int64): [1001, 1002, 1003, 1005, ..., 1020, 1021, 1023, 1025]

In [62]:
pui_df['age'].dtype

dtype('float64')